import 'dart:convert';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:gym_gemini_pro/core/database/database.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:drift/drift.dart' show Value;

class ImportWizardScreen extends ConsumerStatefulWidget {
  const ImportWizardScreen({super.key});

  @override
  ConsumerState<ImportWizardScreen> createState() => _ImportWizardScreenState();
}

enum ImportStep { select, validate, resolve, progress, done }

class _ImportWizardScreenState extends ConsumerState<ImportWizardScreen> {
  ImportStep _currentStep = ImportStep.select;
  Map<String, dynamic>? _importData;
  int _duplicateCount = 0;
  double _progress = 0;
  String _conflictResolution = 'skip'; // skip, replace, all

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Import Data')),
      body: Stepper(
        type: StepperType.horizontal,
        currentStep: _getStepIndex(),
        controlsBuilder: (context, details) => const SizedBox.shrink(),
        steps: [
          Step(title: const Text('File'), isActive: _currentStep == ImportStep.select, state: _getStepState(ImportStep.select), content: _buildFileSelect()),
          Step(title: const Text('Preview'), isActive: _currentStep == ImportStep.validate, state: _getStepState(ImportStep.validate), content: _buildValidation()),
          Step(title: const Text('Resolve'), isActive: _currentStep == ImportStep.resolve, state: _getStepState(ImportStep.resolve), content: _buildConflictResolution()),
          Step(title: const Text('Import'), isActive: _currentStep == ImportStep.progress, state: _getStepState(ImportStep.progress), content: _buildProgress()),
        ],
      ),
    );
  }

  int _getStepIndex() {
    switch (_currentStep) {
      case ImportStep.select: return 0;
      case ImportStep.validate: return 1;
      case ImportStep.resolve: return 2;
      case ImportStep.progress: 
      case ImportStep.done: return 3;
    }
  }

  StepState _getStepState(ImportStep step) {
    if (_currentStep == step) return StepState.editing;
    if (_getStepIndex() > _getStepIndexFor(step)) return StepState.complete;
    return StepState.indexed;
  }

  int _getStepIndexFor(ImportStep step) {
    switch (step) {
      case ImportStep.select: return 0;
      case ImportStep.validate: return 1;
      case ImportStep.resolve: return 2;
      case ImportStep.progress: return 3;
      case ImportStep.done: return 4;
    }
  }

  Widget _buildFileSelect() {
    return Column(
      children: [
        const Icon(LucideIcons.fileJson, size: 64, color: Colors.blue),
        const SizedBox(height: 24),
        const Text('Select a .json backup file generated by GYM Kilo.', textAlign: TextAlign.center),
        const SizedBox(height: 32),
        ElevatedButton(
          onPressed: _pickFile,
          child: const Text('Pick Backup File'),
        ),
      ],
    );
  }

  Future<void> _pickFile() async {
    final result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['json']);
    if (result != null && result.files.single.path != null) {
      final file = File(result.files.single.path!);
      final content = await file.readAsString();
      try {
        final data = jsonDecode(content);
        if (data['gymlog_version'] == null) throw Exception('Invalid backup format');
        
        setState(() {
          _importData = data;
          _currentStep = ImportStep.validate;
        });
      } catch (e) {
        if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Invalid file: $e')));
      }
    }
  }

  Widget _buildValidation() {
    if (_importData == null) return const SizedBox.shrink();
    final counts = {
      'Workouts': (_importData!['workouts'] as List).length,
      'Exercises': (_importData!['custom_exercises'] as List).length,
      'Measurements': (_importData!['body_measurements'] as List).length,
    };

    return Column(
      children: [
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              children: counts.entries.map((e) => Padding(
                padding: const EdgeInsets.symmetric(vertical: 8),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [Text(e.key), Text('${e.value}', style: const TextStyle(fontWeight: FontWeight.bold))],
                ),
              )).toList(),
            ),
          ),
        ),
        const SizedBox(height: 32),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            TextButton(onPressed: () => setState(() => _currentStep = ImportStep.select), child: const Text('Back')),
            ElevatedButton(onPressed: _checkConflicts, child: const Text('Next')),
          ],
        ),
      ],
    );
  }

  Future<void> _checkConflicts() async {
    final db = ref.read(appDatabaseProvider);
    final workouts = await db.select(db.workouts).get();
    final existingWorkoutDates = workouts.map((w) => w.date.toIso8601String()).toSet();
    
    int duplicates = 0;
    final importWorkouts = _importData!['workouts'] as List;
    for (var w in importWorkouts) {
      if (existingWorkoutDates.contains(w['date'])) duplicates++;
    }

    setState(() {
      _duplicateCount = duplicates;
      _currentStep = duplicates > 0 ? ImportStep.resolve : ImportStep.progress;
    });
    
    if (duplicates == 0) _startImport();
  }

  Widget _buildConflictResolution() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Detected $_duplicateCount duplicate workout(s).', style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.orange)),
        const SizedBox(height: 12),
        const Text('How should we handle these?'),
        const SizedBox(height: 24),
        RadioListTile(title: const Text('Skip duplicates'), subtitle: const Text('Only import new data (Recommended)'), value: 'skip', groupValue: _conflictResolution, onChanged: (v) => setState(() => _conflictResolution = v!)),
        RadioListTile(title: const Text('Replace existing'), subtitle: const Text('Overwrite existing workouts with backup data'), value: 'replace', groupValue: _conflictResolution, onChanged: (v) => setState(() => _conflictResolution = v!)),
        RadioListTile(title: const Text('Import all'), subtitle: const Text('Keep everything, even if duplicates are created'), value: 'all', groupValue: _conflictResolution, onChanged: (v) => setState(() => _conflictResolution = v!)),
        const SizedBox(height: 32),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            TextButton(onPressed: () => setState(() => _currentStep = ImportStep.validate), child: const Text('Back')),
            ElevatedButton(onPressed: _startImport, child: const Text('Start Import')),
          ],
        ),
      ],
    );
  }

  Widget _buildProgress() {
    return Column(
      children: [
        const SizedBox(height: 32),
        LinearProgressIndicator(value: _progress),
        const SizedBox(height: 16),
        Text('Importing: ${(_progress * 100).toInt()}%'),
        if (_currentStep == ImportStep.done) ...[
          const SizedBox(height: 32),
          const Icon(LucideIcons.circleCheck, color: Colors.green, size: 48),
          const SizedBox(height: 16),
          const Text('Successfully imported all records!'),
          const SizedBox(height: 24),
          ElevatedButton(onPressed: () => Navigator.pop(context), child: const Text('Finish')),
        ],
      ],
    );
  }

  Future<void> _startImport() async {
    setState(() => _currentStep = ImportStep.progress);
    final db = ref.read(appDatabaseProvider);
    
    await db.transaction(() async {
      // 1. Custom Exercises
      final customExs = _importData!['custom_exercises'] as List;
      for (var ex in customExs) {
        await db.into(db.exercises).insertOnConflictUpdate(Exercise.fromJson(ex));
      }

      // 2. Workouts & Sets
      final importWorkouts = _importData!['workouts'] as List;
      final importSets = _importData!['workout_sets'] as List;
      
      final totalEntries = importWorkouts.length;
      int processed = 0;

      for (var w in importWorkouts) {
          final workoutDate = DateTime.parse(w['date']);
          final isDuplicate = await _isWorkoutDuplicate(db, w);

          if (isDuplicate && _conflictResolution == 'skip') continue;

          if (isDuplicate && _conflictResolution == 'replace') {
             await (db.delete(db.workouts)..where((t) => t.date.equals(workoutDate))).go();
          }
          
          final workout = Workout.fromJson(w);
          final workoutId = await db.into(db.workouts).insert(
            workout.toCompanion(true).copyWith(id: const Value.absent()),
          );
          
          // Import associated sets
          final setsForWorkout = importSets.where((s) => s['workout_id'] == w['id']).toList();
          for (var s in setsForWorkout) {
            final workoutSet = WorkoutSet.fromJson(s);
            await db.into(db.workoutSets).insert(
              workoutSet.toCompanion(true).copyWith(
                id: const Value.absent(),
                workoutId: Value(workoutId),
              ),
            );
          }

          processed++;
          setState(() => _progress = processed / totalEntries);
      }

      // 3. Measurements
      final measurements = _importData!['body_measurements'] as List;
      for (var m in measurements) {
        await db.into(db.bodyMeasurements).insertOnConflictUpdate(BodyMeasurement.fromJson(m));
      }
    });

    setState(() {
      _progress = 1.0;
      _currentStep = ImportStep.done;
    });
  }

  Future<bool> _isWorkoutDuplicate(AppDatabase db, Map<String, dynamic> w) async {
    final date = DateTime.parse(w['date']);
    final match = await (db.select(db.workouts)..where((t) => t.date.equals(date))).getSingleOrNull();
    return match != null;
  }
}
