name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4' # Match pubspec.yaml minimum
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
